### ISSUE TITLE
Remove client id and client secret

### ISSUE THREAD

**Issue by rossiam** [SmartThingsCommunity/dynamodb-context-store-nodejs#1]
These values are global to the application and for security reasons, should not be stored here.

**Comment by erodewald** [comment]
@rossiam, I agree. For the uninitiated, the purpose of the `clientId` and `clientSecret` is to facilitate refreshing the installedapp principle token, but those are `app`-based and should simply be embedded in the host environment for security purposes. They can change too, rendering them useless, so there is no value to having outdated values.

**Comment by erodewald** [comment]
This will not be necessary once #3 is merged
