### ISSUE TITLE
Upgrade aws-sdk to v3 

### ISSUE THREAD

**Issue by rym002** [SmartThingsCommunity/dynamodb-context-store-nodejs#32]
**Is your feature request related to a problem? Please describe.**
aws-sdk v3 is modular and will reduce the dependency size

**Describe the solution you'd like**
Update aws-sdk to v3

**Describe alternatives you've considered**

**Additional context**
See https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html for additional info.

**Comment by bflorian** [comment]
Release of a version using the V3 API is under development and is expected to be released within a couple of weeks.
